firstapp/urls.py
from django.urls import path
from . import views

app_name = 'firstapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('classify/<str:filename>', views.classify, name='classify'),
    path('upload/', views.upload, name='upload')
]

trashorwhat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('firstapp/', include('firstapp.urls')),
]

# 파일을 볼 수 있게 경로 설정함
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstapp/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
import os
import hashlib
from datetime import datetime

#def upload_to_id_image(instance, filename):
#    extension = '.jpg'
#    path = 'train/%(filename)s_%(date_now)s/' % {'filename': filename, 'date_now': datetime.now().strftime("%Y%m%d%H%M%S")}
    #return '%(path)s%(extension)s' % {'path': path, 'extension': extension}

class Post(models.Model):
    image = ProcessedImageField(upload_to='train',
                                #processors=[ResizeToFill(500, 500)],
                                format='JPEG'
                                #options={'quality': 60}
                                )
    
#    image = ProcessedImageField(upload_to='train',
#                                processors=[ResizeToFill(500, 500)],
#                                format='JPEG',
#                                options={'quality': 60})

firstapp/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        #exclude = ('user','like_users')

firstapp/views.py
from django.shortcuts import render, redirect
from fastai.vision import *
from pathlib import Path
from django.conf import settings
import os
from .forms import PostForm
from .models import Post


defaults.device = torch.device('cpu')
#pkl_path = Path("C:\\Users\\KIMSUI\Documents\\17_ai_project\\export-model-3")
pkl_path = os.path.join(settings.MEDIA_ROOT, "pkl")
learn = load_learner(pkl_path)

def classify(filename):
    #img_trash_file = Path("C:\\Users\\KIMSUI\Documents\\10_IITP-AI-Challenge\\nara\\train\\1000\\26536211_1.jpg")
    img_trash_file = os.path.join(settings.MEDIA_ROOT,'train',filename)
    print('----------------------')
    print(img_trash_file)
    print('----------------------')

    img_trash = open_image(img_trash_file)
    pred_class,pred_idx,outputs = learn.predict(img_trash)

    return pred_class.obj

# Create your views here.
def index(request):
    context = {
        'posts' : 'test'
    }
    return render(request, 'firstapp/index.html', context)

def upload(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            # post.image.url -> /media/26536209_1.jpg
            # url = post.image.url
            post.save()
            
            print('----------------------')
            print(post.image.url.split("/")[3])
            print('----------------------')
            
            result_list = classify(post.image.url.split("/")[3])
            
            trash_class = ['일반쓰레기', '종이', '캔류', '유리병', '플라스틱', '비닐', '스티로폼', '음식물']

            for n, i in enumerate(result_list):
                result_list[n] = trash_class[int(i)-1]

            result_str = ''
            for data in result_list:
                result_str = result_str + '#' + data + ' '

            context = {
                'result' : result_str,
                'result_list' : result_list,
                'url' : post.image.url
            }
            
            return render(request, 'firstapp/classify.html', context)
    else:
        form = PostForm()
    context = {
        'form' : form
    }
    return render(request, 'firstapp/form.html', context)

# def save_class(request, result_list):

firstapp/templates/firstapp/classify.html
{% extends 'base.html' %}
{% block content %}
<h3>분류 결과</h3>

<div class="card">
  <h5 class="card-header">
    {{ result }}
  </h5>
  <div class="card-body">
    <img src="{{ url }}" class="card-img-top">
    <p></p>
    <button type="button" class="btn btn-primary"> 정답 </button>
    <button type="button" class="btn btn-danger"> 오답 </button>
    <a href="{% url 'firstapp:upload' %}"><button type="button" class="btn btn-light" > 처음으로 </button></a>
    
  </div>
</div>
</div>
{% endblock %}

firstapp/templates/firstapp/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<h3>분류할 쓰레기 이미지를 선택해주세요</h3>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class='btn btn-primary'>저장</button>
</form>
{% endblock content %}

firstapp/templates/firstapp/index.html
{% extends 'base.html' %}
{% block content %}
<h1> Multi labels for Waste </h1>
<a href="{% url 'firstapp:upload' %}"><button type="button" class="btn btn-light" > 시작하기! </button></a>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/09a70a97c3.js" crossorigin="anonymous"></script>
</head>
<body>
  {% include 'nav.html' %}
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

templates/nav.html
<nav class="nav d-flex justify-content-end my-4">
{% comment '' %}
  <!--{% if user.is_authenticated %}
    <a class="nav-link" href="{% url 'posts:index' %}">피드</a>
    <a class="nav-link" href="{% url 'posts:create' %}">글쓰기</a>
    <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
    <a class="nav-link" href="{% url 'accounts:profile' user.username%}">{{ user.username }} 님</a>
  {% else %}
    <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
    <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
  {% endif %}!-->
{% endcomment %}

</nav>

trashorwhat/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/09a70a97c3.js" crossorigin="anonymous"></script>
</head>
<body>
  {% include 'nav.html' %}
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

trashorwhat/templates/nav.html
<nav class="nav d-flex justify-content-end my-4">
{% comment '' %}
  <!--{% if user.is_authenticated %}
    <a class="nav-link" href="{% url 'posts:index' %}">피드</a>
    <a class="nav-link" href="{% url 'posts:create' %}">글쓰기</a>
    <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
    <a class="nav-link" href="{% url 'accounts:profile' user.username%}">{{ user.username }} 님</a>
  {% else %}
    <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
    <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
  {% endif %}!-->
{% endcomment %}

</nav>